-- ControlLeads — Initial schema
-- Derived from .spec/discovery/entities.md (Etapa 1 aprovada 2026-07-21)
-- Decisions: UUIDs generated by the application · single-tenant · who+when audit
-- on business entities · immutable event tables for status/ownership history.

-- ============================================================================
-- Identity
-- ============================================================================

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    name          VARCHAR(120)  NOT NULL,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    role          VARCHAR(20)   NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_role_valid CHECK (role IN ('ADMINISTRATOR', 'MARKETING_TEAM'))
);

-- ============================================================================
-- Managed catalogs (admin-editable; deactivate, never delete — history refs)
-- ============================================================================

CREATE TABLE courses (
    id         UUID PRIMARY KEY,
    name       VARCHAR(160) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT courses_name_unique UNIQUE (name)
);

CREATE TABLE channels (
    id         UUID PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT channels_name_unique UNIQUE (name)
);

CREATE TABLE stall_reasons (
    id         UUID PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT stall_reasons_name_unique UNIQUE (name)
);

-- ============================================================================
-- Leads (aggregate root)
-- ============================================================================

CREATE TABLE leads (
    id                  UUID PRIMARY KEY,
    full_name           VARCHAR(160) NOT NULL,
    country_code        CHAR(2)      NOT NULL,             -- ISO 3166-1 alpha-2
    email               VARCHAR(255),
    phone               VARCHAR(40),
    course_id           UUID         NOT NULL REFERENCES courses (id),
    channel_id          UUID         NOT NULL REFERENCES channels (id),
    utm_source          VARCHAR(120),
    utm_medium          VARCHAR(120),
    utm_campaign        VARCHAR(160),
    status              VARCHAR(20)  NOT NULL DEFAULT 'LEAD',
    -- Stage the lead was in when marked STALLED; NULL unless status = STALLED.
    stalled_from_status VARCHAR(20),
    stall_reason_id     UUID         REFERENCES stall_reasons (id),
    assigned_to         UUID         NOT NULL REFERENCES users (id),
    -- Denormalized from contact activities (CALL/EMAIL/WHATSAPP/MEETING); SLA input.
    last_contacted_at   TIMESTAMPTZ,
    version             BIGINT       NOT NULL DEFAULT 0,   -- optimistic locking
    created_by          UUID         NOT NULL REFERENCES users (id),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,                       -- soft delete, admin only

    CONSTRAINT leads_status_valid CHECK
        (status IN ('LEAD', 'HOT_LEAD', 'APPLICATION', 'STUDENT', 'STALLED')),
    CONSTRAINT leads_stalled_from_valid CHECK
        (stalled_from_status IN ('LEAD', 'HOT_LEAD', 'APPLICATION')),
    -- STALLED requires the stage it stalled from; other statuses must not carry it.
    CONSTRAINT leads_stalled_consistency CHECK (
        (status = 'STALLED' AND stalled_from_status IS NOT NULL)
        OR (status <> 'STALLED' AND stalled_from_status IS NULL AND stall_reason_id IS NULL)
    ),
    CONSTRAINT leads_contact_present CHECK (email IS NOT NULL OR phone IS NOT NULL)
);

CREATE INDEX idx_leads_assigned_status ON leads (assigned_to, status) WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_status          ON leads (status)              WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_country         ON leads (country_code)        WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_course          ON leads (course_id)           WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_channel         ON leads (channel_id)          WHERE deleted_at IS NULL;
CREATE INDEX idx_leads_created_at      ON leads (created_at);
-- Duplicate detection (warn, don't block — module_leads.md RN-04)
CREATE INDEX idx_leads_email ON leads (lower(email)) WHERE email IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_leads_phone ON leads (phone)        WHERE phone IS NOT NULL AND deleted_at IS NULL;
-- SLA sweep: HOT_LEADs by last contact
CREATE INDEX idx_leads_sla ON leads (last_contacted_at) WHERE status = 'HOT_LEAD' AND deleted_at IS NULL;

-- ============================================================================
-- Immutable event tables (source of truth for all funnel reports)
-- ============================================================================

CREATE TABLE lead_status_events (
    id              UUID PRIMARY KEY,
    lead_id         UUID        NOT NULL REFERENCES leads (id),
    from_status     VARCHAR(20),                -- NULL on creation event
    to_status       VARCHAR(20) NOT NULL,
    stall_reason_id UUID        REFERENCES stall_reasons (id),
    note            TEXT,
    changed_by      UUID        NOT NULL REFERENCES users (id),
    changed_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT lse_from_valid CHECK
        (from_status IN ('LEAD', 'HOT_LEAD', 'APPLICATION', 'STUDENT', 'STALLED')),
    CONSTRAINT lse_to_valid CHECK
        (to_status IN ('LEAD', 'HOT_LEAD', 'APPLICATION', 'STUDENT', 'STALLED')),
    CONSTRAINT lse_stall_reason_only_when_stalled CHECK
        (stall_reason_id IS NULL OR to_status = 'STALLED')
);

CREATE INDEX idx_lse_lead       ON lead_status_events (lead_id, changed_at);
CREATE INDEX idx_lse_transition ON lead_status_events (to_status, changed_at);
CREATE INDEX idx_lse_changed_by ON lead_status_events (changed_by, changed_at);

CREATE TABLE lead_assignment_events (
    id         UUID PRIMARY KEY,
    lead_id    UUID        NOT NULL REFERENCES leads (id),
    from_user  UUID        REFERENCES users (id),   -- NULL on creation
    to_user    UUID        NOT NULL REFERENCES users (id),
    changed_by UUID        NOT NULL REFERENCES users (id),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_lae_lead ON lead_assignment_events (lead_id, changed_at);

-- ============================================================================
-- Engagement
-- ============================================================================

CREATE TABLE activities (
    id           UUID PRIMARY KEY,
    lead_id      UUID        NOT NULL REFERENCES leads (id),
    type         VARCHAR(20) NOT NULL,
    content      TEXT        NOT NULL,
    due_at       TIMESTAMPTZ,            -- FOLLOW_UP only
    completed_at TIMESTAMPTZ,            -- FOLLOW_UP only
    created_by   UUID        NOT NULL REFERENCES users (id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT activities_type_valid CHECK
        (type IN ('NOTE', 'CALL', 'EMAIL', 'WHATSAPP', 'MEETING', 'FOLLOW_UP')),
    CONSTRAINT activities_due_only_followup CHECK
        (due_at IS NULL OR type = 'FOLLOW_UP')
);

CREATE INDEX idx_activities_lead ON activities (lead_id, created_at);
-- "My tasks": open follow-ups by owner, ordered by due date
CREATE INDEX idx_activities_open_followups
    ON activities (created_by, due_at)
    WHERE type = 'FOLLOW_UP' AND completed_at IS NULL;

CREATE TABLE notifications (
    id         UUID PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users (id),
    lead_id    UUID        REFERENCES leads (id),
    type       VARCHAR(30) NOT NULL,
    payload    JSONB       NOT NULL DEFAULT '{}',
    read_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT notifications_type_valid CHECK
        (type IN ('SLA_BREACH', 'FOLLOW_UP_DUE'))
);

CREATE INDEX idx_notifications_user_unread ON notifications (user_id, created_at) WHERE read_at IS NULL;
-- Anti-spam: at most one alert per lead/type/cycle (module_notifications.md RNF-01)
CREATE INDEX idx_notifications_dedup ON notifications (lead_id, type, created_at);

-- ============================================================================
-- Settings (typed key-value)
-- ============================================================================

CREATE TABLE app_settings (
    key        VARCHAR(60) PRIMARY KEY,
    value      JSONB       NOT NULL,
    updated_by UUID        REFERENCES users (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO app_settings (key, value)
VALUES ('hot_lead_max_hours', '24');

-- ============================================================================
-- Seed catalogs (initial values; admin-managed afterwards)
-- ============================================================================

INSERT INTO channels (id, name) VALUES
    (gen_random_uuid(), 'Instagram'),
    (gen_random_uuid(), 'Google Ads'),
    (gen_random_uuid(), 'Facebook'),
    (gen_random_uuid(), 'Education Fair'),
    (gen_random_uuid(), 'Referral'),
    (gen_random_uuid(), 'Website'),
    (gen_random_uuid(), 'Walk-in'),
    (gen_random_uuid(), 'Other');

INSERT INTO stall_reasons (id, name) VALUES
    (gen_random_uuid(), 'Price'),
    (gen_random_uuid(), 'Visa denied'),
    (gen_random_uuid(), 'Chose another school'),
    (gen_random_uuid(), 'No response'),
    (gen_random_uuid(), 'Postponed plans'),
    (gen_random_uuid(), 'Missing documents'),
    (gen_random_uuid(), 'Other');
